version: "3"
services:
  db:
    image: mysql:8.0.26
    container_name: MySQL
    network_mode: host
    volumes:
      - data_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=234oix29l2
      - MYSQL_DATABASE=code_platform
    restart: always
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-time-zone=+08:00'
      - '--max_connections=10000'
      - '--max_user_connections=2200'

  redis:
    image: redis:6.2.7-alpine
    container_name: Redis
    volumes:
      - data_redis:/data
      - ./conf/redis.conf:/redis.conf
      - /var/log/redis:/logs
    network_mode: host
    privileged: true
    restart: always
    command: redis-server /redis.conf

  redis_lru:
    image: redis:6.2.7-alpine
    container_name: Redis-LRU
    volumes:
      - data_redis_lru:/data
      - ./conf/redis_lru.conf:/redis.conf
      - /var/log/redis_lru:/logs
    network_mode: host
    privileged: true
    restart: always
    command: redis-server /redis.conf

  minio:
    image: minio/minio:RELEASE.2021-10-06T23-36-31Z.fips
    container_name: Minio
    volumes:
      - data_minio:/data
    network_mode: host
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "12345678"
      MINIO_BROWSER: "on"
    restart: always
    command: server /data --address ":9100"

  jplag:
    image: lgbgbl/plagiarism-detection:latest
    container_name: JPlag
    network_mode: host
    volumes:
      - data_jplag_report:/reports
      - /code_platform/workspace/codespaces:/code_platform/workspace/codespaces
    restart: always

  ide_server:
    container_name: IDE-Server
    build:
      context: ../api/grpc/ide/service
    network_mode: host
    volumes:
      - data_theia_docker:/var/lib/docker
      - /code_platform/workspace/codespaces:/code_platform/workspace/codespaces
    privileged: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: 2G

  monaco_server:
    container_name: Monaco-Server
    build:
      context: ../api/grpc/monaco/service
    volumes:
      - data_monaco_docker:/var/lib/docker
    network_mode: host
    privileged: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 500M

  node_exporter:
    container_name: NodeExporter
    image: prom/node-exporter:v1.3.1
    command: --web.listen-address=":9099"
    network_mode: host
    restart: always

  prometheus:
    container_name: Prometheus
    image: prom/prometheus:v2.36.1
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - data_prometheus:/prometheus
    network_mode: host
    restart: always
    depends_on:
      - node_exporter

  grafana:
    container_name: Grafana
    image: grafana/grafana:9.0.0
    volumes:
      - data_grafana:/var/lib/grafana
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    network_mode: host
    restart: always
    depends_on:
      - node_exporter
      - prometheus
    entrypoint: sh -c 'grafana-cli admin reset-admin-password werwfion23427 && /run.sh'

  nginx:
    image: nginx:1.21.6-alpine
    container_name: NGINX
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /usr/local/frontend:/usr/share/nginx/html/dist
      - /usr/local/nginx:/var/log/nginx
    restart: always
    ports:
      - 3600:80

volumes:
  data_db:
  data_redis:
  data_redis_lru:
  data_minio:
  data_theia_docker:
  data_monaco_docker:
  data_jplag_report:
  data_prometheus:
  data_grafana:
